PUT http://localhost:8080/events/2
Content-Type: application/json

{
    "name": "Berlin meeting is now updated",
    "description": "meeting of all tech folks in berlin ghat",
    "location": "berlin updated",
    "datetime": "2025-01-01T15:30:00.000Z"
}
